### ISSUE TITLE
Fatal JavaScript invalid size error 169220804 | Data pointer is NULL

### ISSUE THREAD

**Issue by Happypig375** [Carnaux/NFT-Marker-Creator#80]
The two errors in the title are two separate messages. They are for two different images.

Input images:
[scan.PNG](https://user-images.githubusercontent.com/19922066/127744288-b416517a-9e1d-4aec-86b7-842d7e622f7c.PNG)
[scan2.PNG](https://user-images.githubusercontent.com/19922066/127744261-4a9db15f-566e-4c99-8b2a-8c3f9a3cd8d9.png)

Error for scan.PNG: 
```
hadri@Home MINGW64 ~/source/repos/NFT-Marker-Creator (master)
$ node app.js -i ../_3DMappingFestival/_3DMappingFestival.AR/public/an_animated_cat/scan.PNG -dpi=1580
Check output path: C:\Users\hadri\source\repos\NFT-Marker-Creator\output\


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 000000C29BB2E8A0
 1: 00007FF60C37BD2F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+11215
9
 2: 00007FF60C29B11F v8::CFunctionInfo::HasOptions+7039
 3: 00007FF60CF6FD72 V8_Fatal+162
 4: 00007FF60CAE0CD5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedA
rray+101
 5: 00007FF60C99DD02 v8::Object::GetIsolate+17170
 6: 00007FF60C812719 v8::internal::CompilationCache::IsEnabledScriptAndEval+2672
9
 7: 00007FF60CCCFF01 v8::internal::SetupIsolateDelegate::SetupHeap+472849
 8: 0000023D73B91B2D
```
Error for scan2.PNG:
```
hadri@Home MINGW64 ~/source/repos/NFT-Marker-Creator (master)
$ node app.js -i ../_3DMappingFestival/_3DMappingFestival.AR/public/an_animated_cat/scan2.PNG -dpi=790
Check output path: C:\Users\hadri\source\repos\NFT-Marker-Creator\output\

Confidence level: [ - - - - - ] 0/5 || Entropy: 1.37 || Current max: 5.17 min: 4
.6

(6 hours of running this code and lots of output lines later)

[info] (4973, 6137) 790.000000[dpi]
Assertion `mData.get()` failed in /src/emscripten/artoolkit5/lib/SRC/KPM/FreakMatcher/framework/image.cpp line 149: Data pointer is NULL
undefined
undefined
RuntimeError: abort(undefined) at Error
    at jsStackTrace (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:24659)
    at stackTrace (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:24830)
    at abort (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:21515)
    at _abort (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:89134)
    at <anonymous>:wasm-function[265]:0xeed1
    at <anonymous>:wasm-function[1009]:0x5385b
    at <anonymous>:wasm-function[611]:0x25fdf
    at <anonymous>:wasm-function[989]:0x52503
    at <anonymous>:wasm-function[991]:0x52795
    at <anonymous>:wasm-function[942]:0x4fd6e
RuntimeError: abort(undefined) at Error
    at jsStackTrace (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:24659)
    at stackTrace (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:24830)
    at abort (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:21515)
    at _abort (C:\Users\hadri\source\repos\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:89134)
    at <anonymous>:wasm-function[265]:0xeed1
    at <anonymous>:wasm-function[1009]:0x5385b
    at <anonymous>:wasm-function[611]:0x25fdf
    at <anonymous>:wasm-function[989]:0x52503
    at <anonymous>:wasm-function[991]:0x52795
    at <anonymous>:wasm-function[942]:0x4fd6e
```
Full log: [nft-error.txt](https://github.com/Carnaux/NFT-Marker-Creator/files/6911381/nft-error.txt)

**Comment by Happypig375** [comment]
The most infuriating thing about this is how it crashed with 6 hours of wasted computation 😢

**Comment by Happypig375** [comment]
This should be solved by better input checking and error messages.

**Comment by fafrd** [comment]
For anyone visiting this page from Google... I fixed `Fatal JavaScript invalid size error` by using the correct version of Node. I was on v16.11 when the code was building with something much older, v10.19

**Comment by Mohibur-CoU-ICT** [comment]
I am getting the same error message in node.js while working with the Rest API.
The error message I have got is:
```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 000000B871AFE150
 1: 00007FF7EA82013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF7EA73D3CF v8::CFunctionInfo::HasOptions+7055
 3: 00007FF7EB413202 V8_Fatal+162
 4: 00007FF7EAF9CC85 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+101
 5: 00007FF7EAE46483 v8::internal::FeedbackNexus::ic_state+62771
 6: 00007FF7EAE5CFE0 v8::Message::GetIsolate+15840
 7: 00007FF7EACD1731 v8::internal::CompilationCache::IsEnabledScriptAndEval+26849
 8: 00007FF7EB16F3E1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
 9: 000001CF04063757
[nodemon] app crashed - waiting for file changes before starting...
```
I don't know how to solve this.

**Comment by jordanahu** [comment]
I got this same error whilst implementing addAt(node, index) method for a linked list.

**Comment by clebuchegger** [comment]
> For anyone visiting this page from Google... I fixed `Fatal JavaScript invalid size error` by using the correct version of Node. I was on v16.11 when the code was building with something much older, v10.19

downgrading node to version 10 helped me too

**Comment by frontandrew** [comment]
I had same prolem. It was resolved by reinstall `node_modules`.

**Comment by obid2192** [comment]
# Fatal error in , line 0
# Fatal JavaScript invalid size error 170226952
#
#
#
#FailureMessage Object: 00000011B9FFE6D0
 1: 00007FF7BA470AAF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+124015
 2: 00007FF7BA38B55F node::TriggerNodeReport+38223
 3: 00007FF7BB06E392 V8_Fatal+162
 4: 00007FF7BABED205 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+101
 5: 00007FF7BAA967C3 v8::internal::FeedbackNexus::ic_state+62771
 6: 00007FF7BAAAD320 v8::Context::GetIsolate+15840
 7: 00007FF7BA921141 v8::internal::CompilationCache::IsEnabledScriptAndEval+26913
 8: 00007FF7BADBF9C1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
 9: 000002021D32314D

**Comment by obid2192** [comment]
help me

**Comment by Bug-Reaper** [comment]
```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x7ffd2274a0d0
 1: 0x7fa37b2c497b  [/usr/bin/../lib/libnode.so.111]
 2: 0x7fa37bf3cc94 V8_Fatal(char const*, ...) [/usr/bin/../lib/libnode.so.111]
 3: 0x7fa37b79304b  [/usr/bin/../lib/libnode.so.111]
 4: 0x7fa37b93e730  [/usr/bin/../lib/libnode.so.111]
 5: 0x7fa37b93f7a8  [/usr/bin/../lib/libnode.so.111]
 6: 0x7fa37bb590b7 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/../lib/libnode.so.111]
 7: 0x7fa37b4d02f9  [/usr/bin/../lib/libnode.so.111]
Trace/breakpoint trap (core dumped)
```
Same error with both node `v19.1.0` && node ` v16.18.0`.

[X] - Fresh `npm install` did not fix.

**Comment by CrisDaniel** [comment]
In my case, I also got the same error. When I checked my code, it was because I had forgotten to put i++ and my loop was infinite.

**Comment by MosheSchnitzler** [comment]
I got this error when running ng serve. I resolved it by deleting the .angular folder and rerunning ng serve.

**Comment by Abhishek3303Singh** [comment]
I got the same error. After debugging I got the error. I made a mistake in for loop. It was a variable name mistake inside for loop.
